[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
speed_markets = "FnBCKHhKz9KtpqWkWRvfQrWrr8Hs4kbtYE7aTp75F4vj"

[programs.devnet]
speed_markets = "DSVREgjdfRaPTJ37MYBKyvZ3T1jzjjYZKDyTymvVacne"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/kiril/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
